name: build-package

# Only run this when the master branch changes
on:
  push:
  workflow_dispatch:
    #tags:
    #  - "v*"

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install redwrench
        shell: bash -l {0}
        run: |
          pip3 install .
      - name: install PyInstaller
        shell: bash -l {0}
        run: |
          pip3 install pyinstaller==6.6.0
      - name: Build Pyinstaller .exe (macOS and Linux)
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: |
          pyinstaller -n redwrench --onefile --windowed dosview.py
      - name: Build Pyinstaller .exe (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          pyinstaller -n redwrench --onefile dosview.py
      - uses: vimtor/action-zip@v1
        with:
          files: dist/
          recursive: false
          dest: ${{ matrix.os }}-${{github.ref_name}}.zip
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{github.ref_name}}.zip
          path: ${{ matrix.os }}-${{github.ref_name}}.zip
          retention-days: 5
      #- uses: softprops/action-gh-release@v1
      #  with:
      #    files: ${{ matrix.os }}-${{github.ref_name}}.zip
